version: '2'

networks:
  front:
    external: true
  back:
    external: true

volumes:
  gogsdata:
    external: true

services:
  gogs:
    container_name: gogs
    image: gogs/gogs
    networks:
      - front
      - back
    volumes:
      - gogsdata:/data
